### ISSUE TITLE
Pretrained weights

### ISSUE THREAD

**Issue by iakRulan** [BubblyYi/MMPedestron#11]
Hello author, I used the given pre training weights in my training code, but they don't match at all. What's going on?
<img width="674" alt="1731328703463" src="https://github.com/user-<img width="674" alt="1731328703463" src="https://github.com/user-attachments/assets/70453396-caa1-4304-bc33-17dcbd645ff3">

**Comment by iakRulan** [comment]
My trained model has over 700 MB, what's going on?

**Comment by mdfareed92** [comment]
what's going on?
