### ISSUE TITLE
Bad case on obscured human body

### ISSUE THREAD

**Issue by jarheadjoe** [BubblyYi/MMPedestron#4]
![image](https://github.com/user-attachments/assets/0c380412-e098-49a8-967e-1922cbd80b6b)
It happens on crowd-human ckpt

**Comment by jin-s13** [comment]
It looks normal, why do you consider it as a bad case?

Please note that for the crowd-human dataset, we output the **full** bounding box of the human body.

**Comment by iakRulan** [comment]
I would like to ask if there is any mismatch during the weight loading process. I have experienced weight mismatch during both inference and training, and I am not sure where the problem lies.  :(

**Comment by lzm0108** [comment]
> I would like to ask if there is any mismatch during the weight loading process. I have experienced weight mismatch during both inference and training, and I am not sure where the problem lies. :(

have you solved the problem，I met same problem

**Comment by iakRulan** [comment]
> > I would like to ask if there is any mismatch during the weight loading process. I have experienced weight mismatch during both inference and training, and I am not sure where the problem lies. :(
> 
> have you solved the problem，I met same problem

just check cfg
checkpoint_config = dict(interval=1, save_optimizer=False)

**Comment by lzm0108** [comment]
> > > I would like to ask if there is any mismatch during the weight loading process. I have experienced weight mismatch during both inference and training, and I am not sure where the problem lies. :(
> > 
> > 
> > have you solved the problem，I met same problem
> 
> just check cfg checkpoint_config = dict(interval=1, save_optimizer=False)

Thank you very much. I've solved the problem!
