### ISSUE TITLE
problems in testing

### ISSUE THREAD

**Issue by gitac10** [BubblyYi/MMPedestron#8]
when i use the model to testing.
if i use the python 3.6, it shows 

```
Traceback (most recent call last):
  File "tools/test.py", line 22, in <module>
    import mmdet_custom  # noqa: F401,F403
  File "/data/liuyida/liuyida/mmped/MMPedestron-main/mmdet_custom/__init__.py", line 7, in <module>
    from .models import *  # noqa: F401,F403
  File "/data/liuyida/liuyida/mmped/MMPedestron-main/mmdet_custom/models/__init__.py", line 9, in <module>
    from .utils import *  # noqa: F401,F403
  File "/data/liuyida/liuyida/mmped/MMPedestron-main/mmdet_custom/models/utils/__init__.py", line 5, in <module>
    from .transformer import DetrTransformerEncoder_CP
  File "/data/liuyida/liuyida/mmped/MMPedestron-main/mmdet_custom/models/utils/transformer.py", line 5, in <module>
    from fairscale.nn.checkpoint import checkpoint_wrapper
  File "/data/liuyida/liuyida/anaconda3/envs/mmped/lib/python3.6/site-packages/fairscale/__init__.py", line 12, in <module>
    from . import nn
  File "/data/liuyida/liuyida/anaconda3/envs/mmped/lib/python3.6/site-packages/fairscale/nn/__init__.py", line 9, in <module>
    from .data_parallel import FullyShardedDataParallel, ShardedDataParallel
  File "/data/liuyida/liuyida/anaconda3/envs/mmped/lib/python3.6/site-packages/fairscale/nn/data_parallel/__init__.py", line 8, in <module>
    from .fully_sharded_data_parallel import FullyShardedDataParallel, OffloadConfig, TrainingState, auto_wrap_bn
  File "/data/liuyida/liuyida/anaconda3/envs/mmped/lib/python3.6/site-packages/fairscale/nn/data_parallel/fully_sharded_data_parallel.py", line 43, in <module>
    from fairscale.nn.misc import FlattenParamsWrapper
  File "/data/liuyida/liuyida/anaconda3/envs/mmped/lib/python3.6/site-packages/fairscale/nn/misc/__init__.py", line 12, in <module>
    from .flatten_params_wrapper import FlattenParamsWrapper
  File "/data/liuyida/liuyida/anaconda3/envs/mmped/lib/python3.6/site-packages/fairscale/nn/misc/flatten_params_wrapper.py", line 34, in <module>
    from fairscale.experimental.nn.ssd_offload import SsdFlatParameter
  File "/data/liuyida/liuyida/anaconda3/envs/mmped/lib/python3.6/site-packages/fairscale/experimental/nn/ssd_offload.py", line 6
    from __future__ import annotations
    ^
```

so i change the python version to python 3.7. but then I encountered such a problem.

```
  File "/data/liuyida/liuyida/anaconda3/envs/myped37/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory
```

**Comment by PredelinaAsya** [comment]
@gitac10 Good afternoon! Tell me, please, how did you fix this error? Faced the same problem

**Comment by gitac10** [comment]
> @gitac10 Good afternoon! Tell me, please, how did you fix this error? Faced the same problem

I switch to python 3.7 and then reinstall cuda11.0. but it seems i meet other problems。
you can refer this，It seems that the CUDA 11.0 environment is missing.
https://blog.csdn.net/hai4321/article/details/133916420
Is it the former case? At present, I haven't solved it either. If you solve it, can you tell me?

**Comment by PredelinaAsya** [comment]
It turned out to fix a bug with python=3.6 installing a older version of `fairscale==0.4.0`. But after that, a new problem arose: `ModuleNotFoundError: No module named 'petrel_client'.` You wrote about it in the [issue](https://github.com/BubblyYi/MMPedestron/issues/9)

**Comment by gitac10** [comment]
> It turned out to fix a bug with python=3.6 installing a older version of `fairscale==0.4.0`. But after that, a new problem arose: `ModuleNotFoundError: No module named 'petrel_client'.` You wrote about it in the [issue](https://github.com/BubblyYi/MMPedestron/issues/9)

it seems i solve the petrel_client error by modifying the config py
file_client_args=dict(backend='disk')),
try change the backend=petrel_client to backend=disk
![image](https://github.com/user-attachments/assets/a90d066b-158c-4aee-91fb-b3be16380653)
 You can see the explanation in the file_client.py file.
 
![image](https://github.com/user-attachments/assets/b62da224-c4fa-4be0-aa04-9e8b286542a2)

**Comment by PredelinaAsya** [comment]
Thank you! I also fixed a bug with petrel_client. Now there are problems with uploading the dataset. Did you manage to run the pipeline after correcting this error?

**Comment by gitac10** [comment]
> Thank you! I also fixed a bug with petrel_client. Now there are problems with uploading the dataset. Did you manage to run the pipeline after correcting this error?

seems i successfully run the code.
i use the eventped dataset, and modified the mmpedestron_mix5datasets_best.py, get the results corresponding to the paper.i just change the dataset path,and the weight path
![image](https://github.com/user-attachments/assets/7c1df568-874a-4317-8ab0-ddc8fbd4faed)

**Comment by PredelinaAsya** [comment]
@gitac10 Good afternoon! Tell me, please, have you run model on any other datasets?
I have a problem: when running on Crowdhuman validation, metrics are obtained that are much lower than in the paper. If you have run the model on Crowdhuman, please share your metrics and config

**Comment by gitac10** [comment]
> @gitac10 Good afternoon! Tell me, please, have you run model on any other datasets? I have a problem: when running on Crowdhuman validation, metrics are obtained that are much lower than in the paper. If you have run the model on Crowdhuman, please share your metrics and config

good morning. i did't test the crowdhuman validation. maybe you can change the weight and try? as for me ,i test the eventped dataset , it's correspond with the paper. Perhaps modality is also an influencing factor.

**Comment by PredelinaAsya** [comment]
Thanks! I'll try to change the weights. 
Tell me, please, did you change any parameters in the config, except the paths, when run on EventPed?

**Comment by gitac10** [comment]
> Thanks! I'll try to change the weights. Tell me, please, did you change any parameters in the config, except the paths, when run on EventPed?

i think just need simply modify the config to fit datasets,If it is modified properly, only the weight path should be modified.
About modality.For example, for the same weight, in the image modality it may be "map79", and in the event modality it may become 60 or something else.perhaps you can take a closer look at the paper again and see the corresponding relationship between weights and datasets/modalities?

**Comment by iakRulan** [comment]
> > Thank you! I also fixed a bug with petrel_client. Now there are problems with uploading the dataset. Did you manage to run the pipeline after correcting this error?
> 
> seems i successfully run the code. i use the eventped dataset, and modified the mmpedestron_mix5datasets_best.py, get the results corresponding to the paper.i just change the dataset path,and the weight path ![image](https://private-user-images.githubusercontent.com/115990653/379733841-7c1df568-874a-4317-8ab0-ddc8fbd4faed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4NTg5NTksIm5iZiI6MTczMDg1ODY1OSwicGF0aCI6Ii8xMTU5OTA2NTMvMzc5NzMzODQxLTdjMWRmNTY4LTg3NGEtNDMxNy04YWIwLWRkYzhmYmQ0ZmFlZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNlQwMjA0MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZjRlNzliODQzZDhhYmU3N2Y5Y2Q1YjcwOGQ2YzJlNTRjMGM4NzY4MDcyM2UxYTExZTBlNzBhMDZhNGNhMjQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1yJf1_oA3WQp8wAF27y8Dk9vosK6rwF0NpYKWfIMrqE)


Hello, could you please tell me the version of Python and PyTorch you are using? I am currently experiencing some issues with my CUDA environment, like "RuntimeError: CUDA error: no kernel image is available for execution on the device"
And I was wondering if your weights are being loaded from a '.pth' file in a repository. I am encountering reports of "unexpected key in source state_dict: ..." when trying to use them.

**Comment by gitac10** [comment]
> > > Thank you! I also fixed a bug with petrel_client. Now there are problems with uploading the dataset. Did you manage to run the pipeline after correcting this error?
> > 
> > 
> > seems i successfully run the code. i use the eventped dataset, and modified the mmpedestron_mix5datasets_best.py, get the results corresponding to the paper.i just change the dataset path,and the weight path ![image](https://private-user-images.githubusercontent.com/115990653/379733841-7c1df568-874a-4317-8ab0-ddc8fbd4faed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4NTg5NTksIm5iZiI6MTczMDg1ODY1OSwicGF0aCI6Ii8xMTU5OTA2NTMvMzc5NzMzODQxLTdjMWRmNTY4LTg3NGEtNDMxNy04YWIwLWRkYzhmYmQ0ZmFlZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNlQwMjA0MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZjRlNzliODQzZDhhYmU3N2Y5Y2Q1YjcwOGQ2YzJlNTRjMGM4NzY4MDcyM2UxYTExZTBlNzBhMDZhNGNhMjQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1yJf1_oA3WQp8wAF27y8Dk9vosK6rwF0NpYKWfIMrqE)
> 
> Hello, could you please tell me the version of Python and PyTorch you are using? I am currently experiencing some issues with my CUDA environment, like "RuntimeError: CUDA error: no kernel image is available for execution on the device" And I was wondering if your weights are being loaded from a '.pth' file in a repository. I am encountering reports of "unexpected key in source state_dict: ..." when trying to use them.

这个issue前面讨论了python和cuda版本，torch那几个是这样
![image](https://github.com/user-attachments/assets/511cf40e-413d-48d6-be4a-1214eda1e8bf)

**Comment by iakRulan** [comment]
> a

谢谢！我已经成功运行，请教下你有训练过模型吗？我加载了模型权重很多层都不匹配。

**Comment by iakRulan** [comment]
> Thanks! I'll try to change the weights. Tell me, please, did you change any parameters in the config, except the paths, when run on EventPed?

Hello, have you trained the model and obtained your own model weights?

**Comment by PredelinaAsya** [comment]
> > Thanks! I'll try to change the weights. Tell me, please, did you change any parameters in the config, except the paths, when run on EventPed?
> 
> Hello, have you trained the model and obtained your own model weights?

No, I didn't train a new model, I used pre-trained weights from the repository

**Comment by lzm0108** [comment]
> > Thank you! I also fixed a bug with petrel_client. Now there are problems with uploading the dataset. Did you manage to run the pipeline after correcting this error?
> 
> seems i successfully run the code. i use the eventped dataset, and modified the mmpedestron_mix5datasets_best.py, get the results corresponding to the paper.i just change the dataset path,and the weight path ![image](https://private-user-images.githubusercontent.com/115990653/379733841-7c1df568-874a-4317-8ab0-ddc8fbd4faed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwMjg1MDYsIm5iZiI6MTczNDAyODIwNiwicGF0aCI6Ii8xMTU5OTA2NTMvMzc5NzMzODQxLTdjMWRmNTY4LTg3NGEtNDMxNy04YWIwLWRkYzhmYmQ0ZmFlZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMlQxODMwMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MDIzNjM2NmFlYzZhYWQ4NDc1YmQwMmE2ZTY0NWFkMWQyMjIwNjI1NzAzNjlhNjE4NDNkZDBiNGFmY2U4Yzk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.V59wtl6N_WKS_RRjbkDfI-d9UaVBslv1IIbC73FdhCs)

could you please share how you changed weights when run with eventped？

**Comment by lzm0108** [comment]
> > Thank you! I also fixed a bug with petrel_client. Now there are problems with uploading the dataset. Did you manage to run the pipeline after correcting this error?
> 
> seems i successfully run the code. i use the eventped dataset, and modified the mmpedestron_mix5datasets_best.py, get the results corresponding to the paper.i just change the dataset path,and the weight path ![image](https://private-user-images.githubusercontent.com/115990653/379733841-7c1df568-874a-4317-8ab0-ddc8fbd4faed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwMjk5MDgsIm5iZiI6MTczNDAyOTYwOCwicGF0aCI6Ii8xMTU5OTA2NTMvMzc5NzMzODQxLTdjMWRmNTY4LTg3NGEtNDMxNy04YWIwLWRkYzhmYmQ0ZmFlZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMlQxODUzMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MjIxYTQ1MDJjNzQzY2U5Nzg1ZDkxYmUwOTNjNGM5NjViNzNmYTU0MmY1M2QyNDVlYjI5OGU2MzhjYzk0NjY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.VTc-8mJOVdJJEX2ckGfnWkGxKQyWInr___spzgIkPVc)

could I ask which weights file did you use

**Comment by lzm0108** [comment]
> > Thank you! I also fixed a bug with petrel_client. Now there are problems with uploading the dataset. Did you manage to run the pipeline after correcting this error?
> 
> seems i successfully run the code. i use the eventped dataset, and modified the mmpedestron_mix5datasets_best.py, get the results corresponding to the paper.i just change the dataset path,and the weight path ![image](https://private-user-images.githubusercontent.com/115990653/379733841-7c1df568-874a-4317-8ab0-ddc8fbd4faed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0NDk3NTAsIm5iZiI6MTczNDQ0OTQ1MCwicGF0aCI6Ii8xMTU5OTA2NTMvMzc5NzMzODQxLTdjMWRmNTY4LTg3NGEtNDMxNy04YWIwLWRkYzhmYmQ0ZmFlZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxN1QxNTMwNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YTdhNTdjYzY0NGRmMjA5ZjI2ODBhMTg1ZDVjNzA1YjQyODA2MzkzZDBhYjhkZjQ0ZDc0YWMxOWMyNjdjMDI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nWGHW3sxNYE3lh-dxrW2wIaDvoxEnWibnXVWuEddXt8)

hello，I want to ask which file you load from the Eventped dataset link？or everyone in the link should be loaded？

**Comment by gitac10** [comment]
> > > Thank you! I also fixed a bug with petrel_client. Now there are problems with uploading the dataset. Did you manage to run the pipeline after correcting this error?
> > 
> > 
> > seems i successfully run the code. i use the eventped dataset, and modified the mmpedestron_mix5datasets_best.py, get the results corresponding to the paper.i just change the dataset path,and the weight path ![image](https://private-user-images.githubusercontent.com/115990653/379733841-7c1df568-874a-4317-8ab0-ddc8fbd4faed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0NDk3NTAsIm5iZiI6MTczNDQ0OTQ1MCwicGF0aCI6Ii8xMTU5OTA2NTMvMzc5NzMzODQxLTdjMWRmNTY4LTg3NGEtNDMxNy04YWIwLWRkYzhmYmQ0ZmFlZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxN1QxNTMwNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YTdhNTdjYzY0NGRmMjA5ZjI2ODBhMTg1ZDVjNzA1YjQyODA2MzkzZDBhYjhkZjQ0ZDc0YWMxOWMyNjdjMDI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nWGHW3sxNYE3lh-dxrW2wIaDvoxEnWibnXVWuEddXt8)
> 
> hello，I want to ask which file you load from the Eventped dataset link？or everyone in the link should be loaded？

你说的这个link是什么意思？，是说加载那个权重么？我记得是mix5best,下载到本地然后再config文件里面修改权重读取路径就行。不行试试别的

**Comment by lzm0108** [comment]
> > > > Thank you! I also fixed a bug with petrel_client. Now there are problems with uploading the dataset. Did you manage to run the pipeline after correcting this error?
> > > 
> > > 
> > > seems i successfully run the code. i use the eventped dataset, and modified the mmpedestron_mix5datasets_best.py, get the results corresponding to the paper.i just change the dataset path,and the weight path ![image](https://private-user-images.githubusercontent.com/115990653/379733841-7c1df568-874a-4317-8ab0-ddc8fbd4faed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0NDk3NTAsIm5iZiI6MTczNDQ0OTQ1MCwicGF0aCI6Ii8xMTU5OTA2NTMvMzc5NzMzODQxLTdjMWRmNTY4LTg3NGEtNDMxNy04YWIwLWRkYzhmYmQ0ZmFlZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxN1QxNTMwNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YTdhNTdjYzY0NGRmMjA5ZjI2ODBhMTg1ZDVjNzA1YjQyODA2MzkzZDBhYjhkZjQ0ZDc0YWMxOWMyNjdjMDI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nWGHW3sxNYE3lh-dxrW2wIaDvoxEnWibnXVWuEddXt8)
> > 
> > 
> > hello，I want to ask which file you load from the Eventped dataset link？or everyone in the link should be loaded？
> 
> 你说的这个link是什么意思？，是说加载那个权重么？我记得是mix5best,下载到本地然后再config文件里面修改权重读取路径就行。不行试试别的

就是Eventped数据集下载链接里有好几个文件，是需要全部下载还是下载其中一个即可呢？

**Comment by gitac10** [comment]
> > > > > Thank you! I also fixed a bug with petrel_client. Now there are problems with uploading the dataset. Did you manage to run the pipeline after correcting this error?
> > > > 
> > > > 
> > > > seems i successfully run the code. i use the eventped dataset, and modified the mmpedestron_mix5datasets_best.py, get the results corresponding to the paper.i just change the dataset path,and the weight path ![image](https://private-user-images.githubusercontent.com/115990653/379733841-7c1df568-874a-4317-8ab0-ddc8fbd4faed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0NDk3NTAsIm5iZiI6MTczNDQ0OTQ1MCwicGF0aCI6Ii8xMTU5OTA2NTMvMzc5NzMzODQxLTdjMWRmNTY4LTg3NGEtNDMxNy04YWIwLWRkYzhmYmQ0ZmFlZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxN1QxNTMwNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YTdhNTdjYzY0NGRmMjA5ZjI2ODBhMTg1ZDVjNzA1YjQyODA2MzkzZDBhYjhkZjQ0ZDc0YWMxOWMyNjdjMDI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nWGHW3sxNYE3lh-dxrW2wIaDvoxEnWibnXVWuEddXt8)
> > > 
> > > 
> > > hello，I want to ask which file you load from the Eventped dataset link？or everyone in the link should be loaded？
> > 
> > 
> > 你说的这个link是什么意思？，是说加载那个权重么？我记得是mix5best,下载到本地然后再config文件里面修改权重读取路径就行。不行试试别的
> 
> 就是Eventped数据集下载链接里有好几个文件，是需要全部下载还是下载其中一个即可呢？

看你做什么任务，你每次测试肯定只用到一个权重，你可以先都下下来存到本地，然后修改文件的权重路径，用不同的权重试一试看看哪个是你要用的
